name: CI

on: [ push, workflow_dispatch ]

jobs:
  build-on-linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: sudo apt install libtbb-dev

      - name: Configure and build
        run: |
          cmake . -B build
          cmake --build build

  build-on-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019 ]

    steps:
      - uses: actions/checkout@v2

      - name: Configure and build
        run: |
          cmake . -B build -A x64
          cmake --build build --config Release
